project:
  title: "Ian Hulskamp"
  output-dir: ./docs/
  
website:
  title: "Ian Hulskamp" # website top-left corner title 
  favicon: favicon.png
  navbar:
    right:
      - href: index.qmd
        text: Home
        icon: house
      - about.qmd
      - href: skills.qmd
        text: Skills
      - href: interests.qmd
        text: Professional Focus
      - href: blog.qmd
        text: Blog (es)
      - href: "cv/CV-IH-1023.pdf"
        text: CV
      # - icon: twitter
      #   href: https://twitter.com/ihulsk
      # - icon: github
      #   href: https://github.com/ihulsk
    left:
      - href: ../es
        text: Espa√±ol
      - href: ../
        text: English
  site-url: https://ihulsk.github.io/
      
  page-footer: 
    background: light # or dark
    left: 
      - "Copyright 2023, Ian Hulskamp"
    right:
      - icon: twitter
        href: https://twitter.com/ihulsk
      - icon: github
        href: https://github.com/ihulsk
      - icon: linkedin
        href: https://www.linkedin.com/in/ian-hulskamp/
      - icon: envelope
        href: mailto:ihulsk@gmail.com

format:
  html:
    theme:
      light: [sandstone, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    mainfont: Montserrat
    css: styles.css
    toc: true
    page-layout: full

editor: visual

lang: en

